/**
 * Created by neo on 16/4/26.
 */

import config from './config.jsx';

const AppConfig = function (options) {
  const {UA, baseUrl, baseDir} = options;

  const commonPath = `/saas20/api/${config.date}/${UA}`;
  const apiBaseUrl = baseUrl + commonPath;

  return {
    baseInfo: {
      UA: UA,
      host: baseUrl,
      baseDir: baseDir,
      login: baseDir + "/#/signin",
      apiBaseUrl: apiBaseUrl,
      sendSignupCode: apiBaseUrl + "/message/sendcode",
      signup: apiBaseUrl + "/customer/register",
      authMobile: apiBaseUrl + "/customer/authen/mobile",
      resetpwd: apiBaseUrl + "/customer/resetpwd/mobile",
      cookieName: config.cookieName,
      PAGE_SIZE: config.pageSize,
      PAGE_SIZE_25: config.pageSize_25,
      PAGE_SIZE_50: config.pageSize_50
    },
    api: {
      checkSigninUrl: './data/checkSignin.json',
      getTicket: apiBaseUrl + '/customer/getTicket',
      signinUrl: apiBaseUrl + '/staff/authenticate',
      superSigninUrl: apiBaseUrl + '/free/sm/login',
      signoutUrl: apiBaseUrl + '/customer/signout',
      chooseOperation: apiBaseUrl + '/customer/setCurrentStaff',
      managerUrl: './data/room.json',
      loadAreaTree: './data/loadAreaTree.json', //apartment/bill/loadAreaTree
      getAreaList: './data/getAreaList.json',
      getHomeDataUrl: apiBaseUrl + '/analysis/summary/org',
      basic: {
        getCountyList: apiBaseUrl + '/free/basicdata/county',
        getSystemList: apiBaseUrl + '/paramContent/search',
        getOrgCityList: apiBaseUrl + '/basic/orgcity/query',       //运营商城市
        getOpenCityList: apiBaseUrl + '/basic/opencity/query',     //所有开通城市
        getDictList: apiBaseUrl + '/paramContent/search',
        getBillList: apiBaseUrl + '/AptGuest/paramcontent/combox/bill',
        getManagerCenter: apiBaseUrl + "/product/managercenter/list/dic",
        getStaffManagerCenter: apiBaseUrl + "/product/managercenter/staff/query?",
      },
      Housekeeper: {
        getDistributedRoomStatus: apiBaseUrl + "/room/roomregister/queryroomstatus",
        getConcentratedRoomStatus: apiBaseUrl + "",
        getUserManagerList: apiBaseUrl + "/product/managercenter/staff/query?",
        searchRoomByNum: apiBaseUrl + "/room/roomregister/searchroomstatus",
        getDoorlockOperateLogList: apiBaseUrl + "/devicefacade/doorlock/list/operaLog",
        getRoomRenterInfo: apiBaseUrl + "/roomrent/member/detail/tenantHolder/roomId/",
        getRoomOtherRenterList: apiBaseUrl + "/roomrent/member/list/cotenantMembers/roomId/",
        getComplaintAndSuggestionList: apiBaseUrl + "/advice/orgstaff/query",
        getBookingManagementList: apiBaseUrl + "/roomrent/query/bookManage",
        getVacantRoomList: apiBaseUrl + "/roomrent/query/empty",
        getRecentCheckin: apiBaseUrl + "/roomrent/query/recent",
        getRecentCheckout: apiBaseUrl + "/roomrent/query/checkout",
        getManagerCenterListUrl: apiBaseUrl + "/product/managercenter/staff/query",
        getDoorLockPrivilegeListUrl: apiBaseUrl + "/devicefacade/doorlock/list/privilegevo/userGroup/room/",
        getOperaLogListUrl: apiBaseUrl + "/devicefacade/doorlock/list/operaLog",
        getPrivilegeLogListUrl: apiBaseUrl + "/devicefacade/doorlock/list/privilegeLog",
        getRoomDetailInfo: apiBaseUrl + "/room/roomregister/id/%roomId/personId/-999",
        getRoomrentRoomStatusUrl: apiBaseUrl + "/roomrent/query/roomStatus",
        getRoomHistoryPage: apiBaseUrl + "/customer/tenant/history/queryPage"
      },
      Zone: {
        getPersonalInformationUrl: apiBaseUrl + "/customer/regdetail/customerId/",
        updateHeadImage: apiBaseUrl + "/customer/detail/update",
        changePwd: apiBaseUrl + "/customer/changepwd",
      },
      Service: {
        getManagerCenterInfoUrl: apiBaseUrl + '/product/managercenter/list/dic',
        getCurrentDynamicUrl: apiBaseUrl + '/flow/staff/service/webtotal',
        getUpdateServiceUrl: apiBaseUrl + '/flow/staff/service/webquery',
        getManagementOnDetailUrl: apiBaseUrl + '/flow/detail/flowId/',
        getCompAndSuggListUrl: apiBaseUrl + '/advice/orgstaff/query',
        submitReplyInfoUrl: apiBaseUrl + '/advice/reply',
        getEvaluationUrl: './data/GetTestData.json',
        getServiceDetailsUrl: apiBaseUrl + '/free/flow/query/page',
      },
      Apartment: {
        addAreaItem: './data/apartment_add_item.json',
        deleteAreaItem: './data/apartment_add_item.json',
        getApartmentManagerList: apiBaseUrl + '/product/managercenter/query?',
        getCenteralizationDetail: apiBaseUrl + '/product/managercenter/detail?',
        updateCenteralizationDetail: apiBaseUrl + '/product/managercenter/save?',
        deleteCenteralizationDetail: apiBaseUrl + '/product/managercenter/delete?',
        getDecentralizedDetail: './data/apartment_decentralized_detail.json',
        getCenterCityList: './data/apartment_get_city.json',
        getCenterCommunityByCity: apiBaseUrl + '/basicdata/community',
        addCenterCommunity: apiBaseUrl + '/basicdata/community/post',
        getCenterRoomResource: apiBaseUrl + '/house/houseregister/',
        getCenterFloor: './data/apartment_floor.json',
        getApartmentRoomPart: "./data/apartment_center_roompart.json",
        getProductDict: apiBaseUrl + '/product/combox/query?',
        getApartmentPriceScheme: apiBaseUrl + '/aptproduct/resourceprice/querypricescheme/',
        getCountyList: apiBaseUrl + '/free/basicdata/county',
        getCityList: apiBaseUrl + '/basicdata/city/all',
        getOpenCityList: apiBaseUrl + '/basic/opencity/query',
        getBuildingList: apiBaseUrl + '/room/building/',
        getBuildingFloorList: apiBaseUrl + "/room/floor/",
        getFloorRoomList: apiBaseUrl + "/room/roomregisterfloorgroup/",
        getPriceSchemeList: apiBaseUrl + "/aptproduct/resourceprice/getresourceprice/scheme/",
        getApartmentTag: apiBaseUrl + "/free/room/roomtags/",
        getRoomInfo: apiBaseUrl + '/room/roomregister/id/',
        getRoomFeeItem: apiBaseUrl + '/room/arearesources/',
        getFloorRoomBase: apiBaseUrl + '/room/roomregister/',
        modifyApartmentCentralizationHousingRoomStatus: apiBaseUrl + '/room/release',

        getApartmentDecentralized: apiBaseUrl + "/product/managercenter/query",
        getApartmentDecentralizedManagement: apiBaseUrl + "/product/managercenter/detail",
        editApartmentDecentralizedManagement: apiBaseUrl + "/product/managercenter/save?",
        deleteApartmentDecentralizedManagement: apiBaseUrl + "/product/managercenter/delete?",
        getApartmentDecentralizedConfiguration: apiBaseUrl + "/room/roomregistercommunitygroup",
        getApartmentDecentralizedHousingFacilities: apiBaseUrl + "/product/support/query",
        getApartmentDecentralizedHousingFeatures: apiBaseUrl + "/free/room/roomtags/all",
        getApartmentDecentralizedHousingPrices: apiBaseUrl + "/aptproduct/resourceprice/getresourceprice/scheme/",
        getApartmentDecentralizedHousingAparts: apiBaseUrl + "/room/roomregister/relationrooms",
        getApartmentDecentralizedHousingCommunities: apiBaseUrl + "/basicdata/community",
        addApartmentDecentralizedHousingCommunity: apiBaseUrl + "/basicdata/community/post",
        getApartmentDecentralizedHousingSource: apiBaseUrl + "/house/houseregister",
        addApartmentDecentralizedHousingSource: apiBaseUrl + "/house/houseregister/post",
        getApartmentDecentralizedHousingTotal: apiBaseUrl + "/room/roomregister/id/",
        addApartmentDecentralizedHousingTotal: apiBaseUrl + "/room/roomregister/post",
        editApartmentDecentralizedHousingTotal: apiBaseUrl + "/room/roomregister/put",
        deleteApartmentDecentralizedHousingTotal: apiBaseUrl + "/room/roomregister/delete/id/",
        getApartmentDecentralizedHousingApart: apiBaseUrl + "/room/roomregister/id/",
        addApartmentDecentralizedHousingApart: apiBaseUrl + "/room/roomregister/post",
        editApartmentDecentralizedHousingApart: apiBaseUrl + "/room/roomregister/put",
        deleteApartmentDecentralizedHousingApart: apiBaseUrl + "/room/roomregister/delete/id/",
        getApartmentHousing: apiBaseUrl + "/house/houseregister",
        getApartmentHousingDetail: apiBaseUrl + "/house/houseregister",
        getRoomFacilities: apiBaseUrl + '/product/support/query?',
        modifyApartmentDecentralizedHousingRoomStatus: apiBaseUrl + '/room/release',
        getRoomOptionalStatus: apiBaseUrl + "/room/optionalstatus",


        getOpenCityInfoUrl: apiBaseUrl + '/basic/opencity/query',
        getCountyInfoUrl: apiBaseUrl + '/free/basicdata/county',
        getProductInfoUrl: apiBaseUrl + '/product/combox/query',
        getPriceCaseInfoUrl: apiBaseUrl + '/aptproduct/resourceprice/querypricescheme/orgid/',
        getFacilityInfoUrl: apiBaseUrl + "/product/support/query",
        getFeatureInfoUrl: apiBaseUrl + "/free/room/roomtags/all",

        getDistributedUrl: apiBaseUrl + "/product/managercenter/query",
        deleteDistributedManagementUrl: apiBaseUrl + "/product/managercenter/delete",
        getDistributedManagementUrl: apiBaseUrl + "/product/managercenter/detail",
        editDistributedManagementUrl: apiBaseUrl + "/product/managercenter/save",

        getDistributedConfigurationUrl: apiBaseUrl + "/room/roomregistercommunitygroup",


        getDistributedHousingApartsUrl: apiBaseUrl + "/room/roomregister/relationrooms",

        getDistributedHousingRoomUrl: apiBaseUrl + "/room/roomregister/id/",
        getDistributedHousingRoomOnStatusListUrl: apiBaseUrl + "/room/optionalstatus",
        getDistributedHousingRoomOnConfigureStatusUrl: apiBaseUrl + '/room/release',
        editDistributedHousingRoomUrl: apiBaseUrl + "/room/roomregister/put",
        addDistributedHousingRoomUrl: apiBaseUrl + "/room/roomregister/post",
        deleteDistributedHousingRoomUrl: apiBaseUrl + "/room/roomregister/delete/id/",
        getDistributedHousingRoomOnPriceList: apiBaseUrl + "/aptproduct/resourceprice/getresourceprice/scheme/",
        getRoomWhiteList: apiBaseUrl + "/room/whitelist/page",
        reomveFromRoomWhiteList: apiBaseUrl + "/room/whitelist/remove",
        addToRoomWhiteList: apiBaseUrl + "/room/whitelist/add",
        getSysRentPayAck: apiBaseUrl + "/sysRentPayAck/queryAll",
        getRentPayAckList: apiBaseUrl + "/product/managercenter/rentPayAck/page",
        removeMgrRentPayAck: apiBaseUrl + "/product/managercenter/rentPayAck/remove",
        addOneMgrRentPayAck: apiBaseUrl + "/product/managercenter/rentPayAck/add",
        updOneMgrRentPayAck: apiBaseUrl + "/product/managercenter/rentPayAck/update",
        getManagementCenterParametersListUrl: apiBaseUrl + "/aptproduct/centralizedParam/query",
        setParametersAddOrUpdateUrl: apiBaseUrl + "/aptproduct/centralizedParam/save",
        deleteParameterUrl: apiBaseUrl + "/aptproduct/centralizedParam/delete",
      },
      Config: {
        getProductList: apiBaseUrl + '/product/list/query',
        //getProductList: './data/config_product.json',
        getProductDetail: apiBaseUrl + '/product/detail/query',
        deleteProduct: apiBaseUrl + '/product/detail/delete?',
        productEdit: apiBaseUrl + "/product/detail/save?",
        productClone: apiBaseUrl + "/product/detail/clone?",
        service: apiBaseUrl + "/product/service/query",
        updateService: apiBaseUrl + "/product/service/save?",
        getProductParams: apiBaseUrl + "/product/paramcfg/query",
        updateProductParams: apiBaseUrl + "/product/paramcfg/save?",
        getProductAdsList: apiBaseUrl + "/product/advertisement/query?",
        updateProductAd: apiBaseUrl + "/product/advertisement/save?",
        deleteProductAd: apiBaseUrl + "/product/advertisement/delete?",
        getProductFacilities: apiBaseUrl + '/free/room/roomfacilities/all/',
        getSelectAppliances: apiBaseUrl + '/product/support/query?',
        updateRoomFacilities: apiBaseUrl + "/product/support/save?",
        getLeasePolicy: apiBaseUrl + "/aptproduct/leasestrategy",
        updateLeasePolicy: apiBaseUrl + "/aptproduct/leasestrategy/",
        getContractTemplateList: apiBaseUrl + "/aptproduct/template/list",
        updateContractTemplate: apiBaseUrl + "/aptproduct/template/update",
        addContractTemplate: apiBaseUrl + "/aptproduct/template/add",
        getContractTemplateContent: apiBaseUrl + "/pub-interface/contract/templet/getEditorUrl?",
        getAllSubjectList: apiBaseUrl + "/systempara/allsubbillsubject",
        getSubSubjectList: apiBaseUrl + "/systempara/subbillsubject/",
        getProductSubject: apiBaseUrl + "/product/subject/query?",
        saveProductSubject: apiBaseUrl + "/product/subject/save?",
        getBargainList: apiBaseUrl + "/room/roompricespecial",


        getResourcePriceList: apiBaseUrl + "/aptproduct/resourceprice/querypricescheme/orgid/",
        getResourcePriceView: apiBaseUrl + "/aptproduct/resourceprice/queryschemetotal/schemeid/",
        getResourcePriceConfig: apiBaseUrl + "/aptproduct/resourceprice/initconfig",
        updateResourcePriceScheme: apiBaseUrl + "/aptproduct/resourceprice/updatepricescheme",
        addResourcePriceScheme: apiBaseUrl + "/aptproduct/resourceprice/addpricescheme",
        updateResourcePricePrices: apiBaseUrl + "/aptproduct/resourceprice/addprice/schemeid/{id}/prices"
      },
      Financial: {
        getRoomInfoUrl: apiBaseUrl + "/room/roomregister",
        getOrgCityInfoUrl: apiBaseUrl + '/basic/orgcity/query',
        getManageCenterInfoUrl: apiBaseUrl + '/product/managercenter/list/dic',
        getHouseKeeperInfoUrl: apiBaseUrl + '/staff/managercenter/query',
        getBookSubjectInfoUrl: apiBaseUrl + '/systempara/allbooksubject',
        getBillSubjectInfoUrl: apiBaseUrl + '/systempara/allbillsubject',
        getFinancialOfficerInfoUrl: apiBaseUrl + '/staff/managercenter/query',

        getBookJournalUrl: apiBaseUrl + '/financial/platform/getbooks/org',
        getBookJournalOnDownloadUrl: apiBaseUrl + '/free/financial/platform/books/org/download',
        getBookJournalOnNormalSettlementUrl: apiBaseUrl + "/financial/unovoSettlement2OrgInfosByBook",
        getBookJournalOnHandSettlementUrl: apiBaseUrl + "/financial/manualpaymentinfosByPamentId",

        getBillManagementUrl: apiBaseUrl + '/financial/platform/listbills/org',
        getBillManagementOnDownloadUrl: apiBaseUrl + '/free/financial/platform/bills/org/download',
        getBillManagementOnDetailRecordUrl: apiBaseUrl + '/financial/listbilldetails/billid/',
        getBillManagementOnPaymentRecordUrl: apiBaseUrl + '/financial/paymentinfo/billid/',
        getBillManagementOnEditStatusUrl: apiBaseUrl + '/financial/changebillstype/billids/',

        getPlansReceivableUrl: apiBaseUrl + '/contract/rentPayPlan/list',
        getPlansReceivableOnPlanOptionUrl: apiBaseUrl + '/contract/rentPayPlan/list/planItem/planId/',

        getManualCheckinUrl: apiBaseUrl + '/financial/manualpaymentinfos',
        getManualCheckinOnPaymentBillUrl: apiBaseUrl + '/financial/getbills/paymentId/',

        getPlatformCheckoutUrl: apiBaseUrl + '/financial/unovoSettlement2OrgInfos',
        getPlatformCheckoutOnBookRecordUrl: apiBaseUrl + '/financial/getbook/applicationId/',
        getPlatformCheckoutOnLoanRecordUrl: apiBaseUrl + '/financial/unovoTransferOut2OrgInfos/',
        getPlatformCheckoutOnDownloadRecordUrl: apiBaseUrl + '/free/financial/getbook/download/',

        getHousekeeperCheckoutInitUrl: apiBaseUrl + '/financial/manualpaymentbills',
        getHousekeeperCheckoutInfoUrl: apiBaseUrl + '/financial/manualpaymentbill/details/settlementId/',
        getHousekeeperCheckoutInfoOnSettleBillUrl: apiBaseUrl + '/financial/manualpayment/settlement/billoff',
        getHousekeeperCheckoutInfoOnProcessErrorsUrl: apiBaseUrl + '/financial/manualpaymentbill/processerrors',
        getHousekeeperCheckoutInfoOnErrorsDetailUrl: apiBaseUrl + '/financial/manualpaymentbill/errorRevised/',
        getHousekeeperCheckoutInfoOnErrorsHistoryUrl: apiBaseUrl + '/financial/manualpaymentbill/queryerrors',

        getRenterRefundUrl: apiBaseUrl + '/flow/refund/request/query',
        getRenterRefundOnCheckRightUrl: apiBaseUrl + '/flow/claim',
        getRenterRefundOnStartApprovalUrl: apiBaseUrl + '/flow/refund/check',
        getRenterRefundOnCloseApprovalUrl: apiBaseUrl + '/flow/close',

        getCompanyStamp: apiBaseUrl + '/org/companySeal/query/orgId',
        updateCompanyStamp: apiBaseUrl + '/org/companySeal/upload',
        enableCompanyStamp: apiBaseUrl + '/org/companySeal/enable',

        getPredepositJournalUrl: apiBaseUrl + '/financial/upms/preDeposit/records',
        getRoomBalanceUrl: apiBaseUrl + "/advice/orgstaff/query",
        getRoomPreDepositDataUrl: apiBaseUrl + "/customer/room/balance/query?",
        setPreDepositDataUrl: apiBaseUrl + "/financial/withdrawal2balance",
        chargeMoney: apiBaseUrl + "/financial/prerecharge/prerechargebycash",
        getRechargeAudit: apiBaseUrl + "/financial/prerecharge/queryprerechargebycashpage",
        auditRecharge: apiBaseUrl + "/financial/prerecharge/settlement",

        getSettlementApprovalUrl: apiBaseUrl + '/flow/approval/query',
        getSettlementApprovalOnDetailUrl: apiBaseUrl + '/flow/approval/detail',
        getSettlementApprovalOnApprovalUrl: apiBaseUrl + '/flow/approval/check',

      },
      Finance: {
        getOperatorInfoUrl: apiBaseUrl + '/organization/query/page',
        getOpenCityInfoUrl: apiBaseUrl + '/basic/opencity/query',
        getSubjectInfoUrl: apiBaseUrl + '/payingconfig/items',
        getCustomerInfoByPhoneUrl: apiBaseUrl + '/customer/register/query/mobile',
        getRoomInfoUrl: apiBaseUrl + "/room/roomregister",
        getOrgCityInfoUrl: apiBaseUrl + '/basic/orgcity/query',
        getManageCenterInfoUrl: apiBaseUrl + '/product/managercenter/list/dic',
        getHouseKeeperInfoUrl: apiBaseUrl + '/staff/managercenter/query',
        getBookSubjectInfoUrl: apiBaseUrl + '/systempara/allbooksubject',
        getBillSubjectInfoUrl: apiBaseUrl + '/systempara/allbillsubject',
        getFinancialOfficerInfoUrl: apiBaseUrl + '/staff/managercenter/query',
        getStampUrl: apiBaseUrl + '/org/companySeal/query/orgId',
        setEnableUrl: apiBaseUrl + '/org/companySeal/enable',
        saveStampUrl: apiBaseUrl + '/org/companySeal/upload',
        getCurrentLeaselistUrl: apiBaseUrl + '/property/accountsrecord/query',
        accountsRecordSaveUrl: apiBaseUrl + '/property/accountsrecord/save',
        getSubjectDataUrl: apiBaseUrl + '/property/accountsrecord/querylist',
        getPropertyDetailUrl: apiBaseUrl + '/house/financial/property/',
        propertyRentalsListUrl: apiBaseUrl + '/financial/platform/getbooks/org',

        Todo: {
          getTodoListURL: apiBaseUrl + "/flow/query/staff/task",
          getTodoDetailURL: apiBaseUrl + "/flow/query/task/detail",
          getTodoHistoryListURL: apiBaseUrl + "/flow/query/task/his",
          approveBillURL: apiBaseUrl + "/flow/task/approval",
          approveBillsURL: apiBaseUrl + "/flow/task/approval/batch"
        },
        Contract: {
          getContractPropertyListURL: apiBaseUrl + '/house/contract/queryPage',
          getContractPropertyDetailURL: apiBaseUrl + '/house/propertycontract/',
          getContractPropertyOperationURL: apiBaseUrl + '/AptGuest/house/contract/{contract}/oper'
        },
        Bill: {
          getBillPropertyListURL: apiBaseUrl + '/financial/listbills'
        }
      },
      PaymentSetting: {
        getManagementPayConfig: apiBaseUrl + '/center/payingconfig/',
        getOrgPaymentSubjectList: apiBaseUrl + '/org/{orgId}/payingconfig',
        getPropertyPayConfig: apiBaseUrl + '/property/payingconfig/',
      },
      Organization: {
        getDepartmentList: apiBaseUrl + "/department/query?",
        saveDepartmentInfo: apiBaseUrl + "/department/save?",
        deleteDepartmentInfo: apiBaseUrl + "/department/delete?",
        getStaffList: apiBaseUrl + "/staff/query/page?",
        getRoleList: apiBaseUrl + "/role/combox/load?",
        getRolesWorkClassList: apiBaseUrl + "/workschedule/query?",
        updateRolesWorkClass: apiBaseUrl + "/workschedules/save?",
        deleteWorkClass: apiBaseUrl + "/workschedule/delete?",
        getWorkPlanList: apiBaseUrl + "/workplan/query?",
        getRolesDutyList: apiBaseUrl + "/duty/query/combox?",
        getRoleManagerCenter: apiBaseUrl + "/staff/managercenter/tree?",
        getManagerCenterRoom: apiBaseUrl + "/staff/center/roleduty/tree?",
        getAttendance: apiBaseUrl + "/attendance/getAttendList?",
        getStaff: apiBaseUrl + "/staff/query/page?",
        getCustomerInfo: apiBaseUrl + "/customer/register/query?",
        updateStaff: apiBaseUrl + "/staff/save?",
        getStaffDetail: apiBaseUrl + "/staff/detail/staffId/",
        deleteStaff: apiBaseUrl + "/staff/delete?",
        getDutyList: apiBaseUrl + "/staff/query/onwork?",
        getStaffTask: apiBaseUrl + "/flow/query/staff?",
        upLoadWrokSechdule: apiBaseUrl + "/workplan/schedule/checkin",
        downLoadWrokSechdule: apiBaseUrl + "/workplan/checkout",
        getCustomerInfoByMobile: apiBaseUrl + "/customer/register/query/mobile", //根据手机号查询注册号信息,
        getBankAccount: apiBaseUrl + "/org/offlineaccount/",
      },
      PriceScheme: {
        getConfigPriceScheme: apiBaseUrl + "/aptproduct/resourceprice/querypricescheme/orgid/",
        getConfigPriceSchemeInit: apiBaseUrl + "/aptproduct/resourceprice/initconfig",
        getConfigPriceSchemeShow: apiBaseUrl + "/aptproduct/resourceprice/queryschemetotal/schemeid/",
        deleteConfigPriceScheme: apiBaseUrl + "/aptproduct/resourceprice/deletepricescheme/schemeid/",
        editConfigPriceScheme: apiBaseUrl, //using
        getConfigPriceSchemeV2: apiBaseUrl + "/aptproduct/resourceprice/query/scheme/{scheme}/subject/{subject}"
      },
      MemberManage: {
        getMemberList: apiBaseUrl + "/crm/orgVip/list/vipInfo",
        getBlackMemberList: apiBaseUrl + "/crm/orgVip/list/blackVips",
        getMemberBasicInfo: apiBaseUrl + "/customer/perdetail/orgId/",
        getBlackListHistoryList: apiBaseUrl + "/crm/orgVip/list/blackHistory",
        setBlackListHistoryList: apiBaseUrl + "/crm/orgVip/blackStatus/set",
        getReasonData: apiBaseUrl + "/paramContent/search",
        getCompAndSuggList: apiBaseUrl + "/advice/query",
        getRentRecordList: apiBaseUrl + "/crm/orgVip/list/rentHistories",

        getContractUrl: apiBaseUrl + "/rent/contract/query/items",
        getContractOnDetailRecordUrl: apiBaseUrl + "/rent/contract/query/",
        getContractOnAddContractUrl: apiBaseUrl + "/roomrent/checkinOffline",
        getContractOnAddAttachmentUrl: apiBaseUrl + "/rent/contract/attachment/upload",
        getContractOnDownloadContractUrl: apiBaseUrl + "/rent/contract/download",
        getContractOnUploadContractUrl: apiBaseUrl + '/roomrent/import/checkinfo',
        getContractOnSoftCopyContractUrl: apiBaseUrl + '/contract/view/',
        getContractOnCheckoutUrl: apiBaseUrl + '/roomrent/cancelCheckin',
        getContractOnPayModeUrl: apiBaseUrl + '/contract/modify',
        contractProgressSearchUrl: apiBaseUrl + '/batchTask/query',
        contractProgressDetail: apiBaseUrl + '/batchTaskDetail/query',

        getRoomInfoUrl: apiBaseUrl + "/room/roomregister"
      },
      Lock: {
        getLockControlLog: apiBaseUrl + '/devicefacade/doorlock/list/operaLog',
        getLockList: apiBaseUrl + '/devicefacade/doorlock/list/doorlocks',
        getLockAuthPageList: apiBaseUrl + '/devicefacade/doorlock/list/privilegePageVos',
        addLockAuth: apiBaseUrl + '/doorlock/batchAdd',
        installLock: apiBaseUrl + '/devicefacade/doorlock/add/grantByLockadd',
      },
      Message: {
        getMessageList: apiBaseUrl + "/messsage/app/query/page",
        getMessageDetail: apiBaseUrl + "/message/detail/messageId/",
        getCityMgrCenterList: apiBaseUrl + "/product/managercenter/staff/query/citygroup",
        sendMsgToMgrCenterRenters: apiBaseUrl + "/messsage/send/area",
      },
      Customer: {
        getCustomerInfoByMobile: apiBaseUrl + "/customer/register/query/mobile"
      },
      Report: {
        getGuestRoomSummary: apiBaseUrl + "/analysis/count/room",
        getGuestRoomRental: apiBaseUrl + "/analysis/count/historyRentRate",
        getGuestRoomSum: apiBaseUrl + "/analysis/count/historyRoom",
        getGuestRoomIncrease: apiBaseUrl + "/analysis/count/historyGrowthRoom",
        getEnergyRankings: apiBaseUrl + "/analysis/count/historyGrowthRoom",
        getStatisticsListUrl: apiBaseUrl + "/analysis/energy/center/",
        getExcelUrl: apiBaseUrl + "/analysis/energy/roomSummary/download",
        getChartDataListUrl: './data/report_energy_chartData.json',
        getSummaryDataUrl: './data/report_energy_summary.json',
        getCustomerDataUrl: apiBaseUrl + "/analysis/stat/room/customer",
        getRoomInfoUrl: apiBaseUrl + "/analysis/stat/room/info",
        getRepairRecordUrl: apiBaseUrl + "/analysis/stat/room/repairrecord",
        getRoomFacilitiesUrl: apiBaseUrl + "/analysis/stat/room/facilities",
        getEmptyRoomUrl: apiBaseUrl + "/analysis/stat/room/empty",
        Energy: {
          //overview
          getCurrentPower: apiBaseUrl + "/analysis/energy/center/{centerId}/curPower",
          getTodayUsed: apiBaseUrl + "/analysis/energy/center/{centerId}/energy/today",
          getThisMonthUsed: apiBaseUrl + "/analysis/energy/center/{centerId}/energy/thisMonth",
          getLastMonthUsed: apiBaseUrl + "/analysis/energy/center/{centerId}/energy/lastMonth",
          getTodayConsumption: apiBaseUrl + "/analysis/energy/center/{centerId}/energyPerHour/today",
          getYesterdayConsumption: apiBaseUrl + "/analysis/energy/center/{centerId}/energyPerHour/yesterday",
          //groups
          Groups: {
            day: apiBaseUrl + "/analysis/energy/center/%center/itemEnergyPerHour/all/day/%date",
            month: apiBaseUrl + "/analysis/energy/center/%center/itemEnergyPerDay/all/month/%date",
            year: apiBaseUrl + "/analysis/energy/center/%center/itemEnergyPerMonth/all/year/%date",
          },
          //ranking
          Ranking: {
            day: apiBaseUrl + "/analysis/energy/center/%center/roomEnergy/all/day/%date",
            month: apiBaseUrl + "/analysis/energy/center/%center/roomEnergy/all/month/%date",
            year: apiBaseUrl + "/analysis/energy/center/%center/roomEnergy/all/year/%date",
          },
          //trending
          Trending: {
            day: apiBaseUrl + "/analysis/energy/center/%center/energyPerHour/day/%date",
            month: apiBaseUrl + "/analysis/energy/center/%center/energyPerDay/month/%date",
            year: apiBaseUrl + "/analysis/energy/center/%center/energyPerMonth/year/%date",
          },
          TimingDiagram: apiBaseUrl + "/analysis/que/svcValSeq/td/{deviceId}/start/{start}/end/{end}",
          getPropertyList: apiBaseUrl + "/analysis/que/property/center/{centerId}/type/{centerType}",  //todo Deprecated
          getHousePropertyList: apiBaseUrl + "/house/center/{centerId}/properties",
          getConcentrationRoomList: apiBaseUrl + "/analysis/que/property/building/{buildingId}", //todo Deprecated
          getHouseConcentrationRoomList: apiBaseUrl + "/house/property/{property}/rooms",
          getPropertyDataListNew: apiBaseUrl + "/analysis/energy/property/qd/{qd}/type/{areaType}/start/{startTime}/end/{endTime}/{propertyId}",
          getPropertyDataList: apiBaseUrl + "/analysis/energy/property/{propertyId}/type/{areaType}/start/{startTime}/end/{endTime}"
        },
        getMemberAndTenantUrl: apiBaseUrl + "/anls/member/today/org/",
        getMemberHistoryUrl: apiBaseUrl + "/anls/member/vip/history",
        Finance: {
          getIOCompareUrl: apiBaseUrl + "/anls/fi/history/all",
          getIncomeUrl: apiBaseUrl + "/anls/fi/history/income",
          getExpenditureUrl: apiBaseUrl + "/anls/fi/history/expenditure",
          getUnpaidAmtUrl: apiBaseUrl + "/anls/fi/history/notpay/money",
          getUnpaidCntUrl: apiBaseUrl + "/anls/fi/history/notpay/count",
          getExpiredAmtUrl: apiBaseUrl + "/anls/fi/history/overdue/money",
          getExpiredCntUrl: apiBaseUrl + "/anls/fi/history/overdue/count",
          getCurrentTargetsUrl: apiBaseUrl + "/anls/fi/target/org/%org",
        }
      },
      Maintain: {
        getDeviceStatus: apiBaseUrl + '/devicefacade/device/query/status',
        getCentralizedLock: apiBaseUrl + "/doorlock/centergroup",
        getDistributedLock: apiBaseUrl + "/doorlock/dispersedgroup",
        addLock: apiBaseUrl + "/doorlock/post",
        deleteLock: apiBaseUrl + "/doorlock/delete/id/",
        updateLock: apiBaseUrl + "/doorlock/put",
        getNodeLockList: apiBaseUrl + "/doorlock",
        getDeviceConfigList: {
          center: apiBaseUrl + "/saasbossrelation/center",
          distributed: apiBaseUrl + "/saasbossrelation/dispersed"
        },
        submitDeviceConfigList: apiBaseUrl + "/saasbossrelation/relation",
        getDevices: apiBaseUrl + "/devicefacade/device/list/baid/{baid}",
        getSystemParameterListUrl: apiBaseUrl + "/org/param/query",
        deleteSystemParameterUrl: apiBaseUrl + "/org/param/delete",
        saveSystemParameterUrl: apiBaseUrl + "/org/param/save",
      },
      HouseResource: {
        getHouseList: apiBaseUrl + "/house/property/pageview",
        backAuditActionUrl: apiBaseUrl + "/house/property/%propertyId/back",
        getHomeOwnerListUrl: apiBaseUrl + "/house/proprietor/pageview",
        getOwnerStatusListUrl: apiBaseUrl + "/paramContent/search",
        getOwnerUrl: apiBaseUrl + "/house/proprietor/",
        editOwnerInfoUrl: apiBaseUrl + "/house/",
        getHouseConfigList: apiBaseUrl + "/house/facilities/query/%id",
        distributedSubmit: apiBaseUrl + "/house/houseRegister/saveOrUpdate",
        getHouseResourceDetail: apiBaseUrl + "/house/houseRegister/query/%id",
        getHouseResourceDetailView: apiBaseUrl + "/house/property/%id/detailsview",
        getHouseResourceDetailEditInit: apiBaseUrl + "/house/property/%id",
        doSave: apiBaseUrl + "/house/property",
        getConfigurationCostUrl: apiBaseUrl + "/house/houseFee/query/",
        setConfigCostUpdateUrl: apiBaseUrl + "/house/houseFee/add/batch",
        getPaymentList: apiBaseUrl + "/house/payPlan/query/record/house/%id",
        getRoomFacilitiesUrl: apiBaseUrl + "/free/room/roomfacilities/all/",
        getBankListUrl: apiBaseUrl + "/paramContent/search",

        getContractUrl: apiBaseUrl + "/property/contract/query",
        getContractHistoryUrl: apiBaseUrl + "/property/{propertyId}/contract/history",
        editContractUrl: apiBaseUrl + "/property/contract/save",
        getContractPartyAUrl: apiBaseUrl + '/house/proprietor/{proprietorId}/updateview',
        editContractPartyAUrl: apiBaseUrl + "/house/{propertyId}/proprietor",
        getPropertyDelivery: apiBaseUrl + "/property/delivery/query",
        getAllMyFacility: apiBaseUrl + "/property/%id/facility",
        getLifepayCompanyByType: apiBaseUrl + "/house/lifepayCompany/select?type=%type",
        addLifepayCompany: apiBaseUrl + "/house/lifepayCompany",
        propertyDeliverySave: apiBaseUrl + "/property/delivery/save",
        propertyDetailFileUpload: apiBaseUrl + "/house/property/batch",
        propertyProprietorFileUpload: apiBaseUrl + "/house/proprietor/batch",
        propertyContractFileUpload: apiBaseUrl + "/house/contract/batch",
        propertyDeliveryFileUpload: apiBaseUrl + "/house/delivery/batch",
        getPropertyMountedHouses: apiBaseUrl + "/house/propertyroomreflistview",
        getUnmountedPropertyHouses: apiBaseUrl + "/house/property/%propertyId/roomview",
        mountedPropertyHouses: apiBaseUrl + "/house/propertyroomref",
        unmountedPropertyHouses: apiBaseUrl + "/house/propertyroomref/del",
      },
      OperationDaily: {
        getSummaryList: apiBaseUrl + "/analysis/summary/business/subject",
        getSummary: apiBaseUrl + "/analysis/summary/business",
        getVacantRoomList: apiBaseUrl + "/roomrent/query/empty",
      },
      DataHandler: {
        importData: apiBaseUrl + "/roomrent/import/common",
        batchTaskUrl: apiBaseUrl + "/batchTask/query",
        batchTaskDetailUrl: apiBaseUrl + "/batchTaskDetail/query",
        getOperatorsUrl: apiBaseUrl + '/organization/query/page',
        getManagerCenterListUrl: apiBaseUrl + '/product/managercenter/query',
        uploadContractFileUrl: apiBaseUrl + '/roomrent/import/checkinfo',
        uploadGuestRoomFileUrl: apiBaseUrl + '/room/import',
        uploadFeeFileUrl: apiBaseUrl + '/room/resource/import',
        contractProgressSearchUrl: apiBaseUrl + '/batchTask/query',
      },
      ShareResources: {
        getResourcesInfo: apiBaseUrl + "/shareRes/config/query/key",
        getResourcesInfoDetail: apiBaseUrl + "/shareRes/config/query/id/",
        getDevicesType: apiBaseUrl + "/shareResType/que/all",
        getTargetDeviceList: apiBaseUrl + "/devicefacade/device/list/baid/{baid}",
        updateShareResource: apiBaseUrl + "/shareRes/config/update",
        addShareResource: apiBaseUrl + "/shareRes/config/add",
        deleteShareResource: apiBaseUrl + "/shareRes/config/delete/{id}"
      },
      AssetOperation: {
        getElectricContractList: apiBaseUrl + '/assetbusiness/contractOperating/query',
        getPropertyList: apiBaseUrl + '/house/pagePropertyVo',
        addRelationProperty: apiBaseUrl + '/assetbusiness/contractProperty/save',
        relieveRelationProperty: apiBaseUrl + '/assetbusiness/contractProperty/disAssociate',
        deliverProperty: apiBaseUrl + '/assetbusiness/contractproperty/delivery/save',
        getOrganization: apiBaseUrl + '/organization/query/list',
        getAptWithContractOrg: apiBaseUrl + '/property/consumerecord/statistics/org',
        saveContract: apiBaseUrl + '/assetbusiness/contractOperating/save',
        getRechargeRecordListUrl: apiBaseUrl + '/property/consumerecord/statistics/page',
        getCityListUrl: apiBaseUrl + '/property/consumerecord/statistics/city',
        getOperatorListUrl: apiBaseUrl + '/property/consumerecord/statistics/org',
        getMeterReaderListUrl: apiBaseUrl + '/property/consumerecord/statistics/assetmeterreader',
        getAmountMonitoringListUrl: apiBaseUrl + '/property/consumerecord/amount/statistics/page',
        // getAmountMonitoringListUrl: './data/meterReadingStatistics.json',
      },
      Others: {
        test: apiBaseUrl + "/estate/estateCategory/list"
      },
      AssetManage: {
        getAssetCategory: apiBaseUrl + "/estate/estateCategory/list",
        getAllAssetCategory: apiBaseUrl + "/estate/estateCategory/selectAll",
        getAssetBrand: apiBaseUrl + "/estate/estateCategoryBrand/list",
        getAssetStandard: apiBaseUrl + "/estate/estateSpec/list",
        getAssetModel: apiBaseUrl + "/estate/estateModel/list",
      }
    }
  };
};

export default AppConfig;
